server:
  port: 8083

spring:
  application:
    name: crew-service
  config:
    import: classpath:db-common.yml
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name} 