repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        files: \.md$
        args: ["-c", "docs/docs-tools/.markdownlint.jsonc"]
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.15.4
    hooks:
      - id: cspell
        files: \.md$
        args: ["--config", "docs/docs-tools/cspell.json", "--no-progress", "--show-context"]
  - repo: local
    hooks:
      - id: vale
        name: vale
        entry: bash -c 'cd docs/docs-tools && vale ..'
        language: system
        types: [markdown]
        files: \.md$
      - id: lychee
        name: lychee
        entry: bash -c 'cd docs/docs-tools && lychee --config lychee.toml ..'
        language: system
        types: [markdown]
        files: \.md$
