openapi: 3.0.3
info:
  title: AquaStream Frontend API
  description: HTTP API для взаимодействия с фронтенд приложением
  version: 1.0.0
  contact:
    name: AquaStream Team
servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://aquastream.org
    description: Production server

tags:
  - name: Pages
    description: Операции с веб-страницами
  - name: Static
    description: Статические ресурсы
  - name: API Proxy
    description: Проксирование запросов к backend

paths:
  /:
    get:
      tags: [Pages]
      summary: Главная страница
      description: Возвращает главную страницу приложения
      responses:
        '200':
          description: HTML страница
          content:
            text/html:
              schema:
                type: string
                example: "<!DOCTYPE html><html>...</html>"

  /events:
    get:
      tags: [Pages]
      summary: Страница событий
      description: Список всех доступных событий
      responses:
        '200':
          description: HTML страница со списком событий
          content:
            text/html:
              schema:
                type: string

  /events/{id}:
    get:
      tags: [Pages]
      summary: Детальная страница события
      description: Подробная информация о конкретном событии
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID события
      responses:
        '200':
          description: HTML страница события
          content:
            text/html:
              schema:
                type: string
        '404':
          description: Событие не найдено
          content:
            text/html:
              schema:
                type: string

  /profile:
    get:
      tags: [Pages]
      summary: Профиль пользователя
      description: Страница профиля текущего пользователя
      security:
        - bearerAuth: []
      responses:
        '200':
          description: HTML страница профиля
          content:
            text/html:
              schema:
                type: string
        '401':
          description: Пользователь не авторизован
          content:
            text/html:
              schema:
                type: string

  /login:
    get:
      tags: [Pages]
      summary: Страница входа
      description: Форма авторизации пользователя
      responses:
        '200':
          description: HTML страница входа
          content:
            text/html:
              schema:
                type: string

  /register:
    get:
      tags: [Pages]
      summary: Страница регистрации
      description: Форма регистрации нового пользователя
      responses:
        '200':
          description: HTML страница регистрации
          content:
            text/html:
              schema:
                type: string

  /api/{proxy+}:
    get:
      tags: [API Proxy]
      summary: Проксирование GET запросов
      description: Проксирует GET запросы к backend API
      parameters:
        - name: proxy+
          in: path
          required: true
          schema:
            type: string
          description: Путь к backend endpoint
      responses:
        '200':
          description: Успешный ответ от backend
          content:
            application/json:
              schema:
                type: object
        default:
          description: Ошибка от backend
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags: [API Proxy]
      summary: Проксирование POST запросов
      description: Проксирует POST запросы к backend API
      parameters:
        - name: proxy+
          in: path
          required: true
          schema:
            type: string
          description: Путь к backend endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Успешный ответ от backend
          content:
            application/json:
              schema:
                type: object
        default:
          description: Ошибка от backend
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /static/{resource}:
    get:
      tags: [Static]
      summary: Статические ресурсы
      description: CSS, JS, изображения и другие статические файлы
      parameters:
        - name: resource
          in: path
          required: true
          schema:
            type: string
          description: Путь к статическому ресурсу
      responses:
        '200':
          description: Статический файл
          content:
            text/css:
              schema:
                type: string
            application/javascript:
              schema:
                type: string
            image/*:
              schema:
                type: string
                format: binary
        '404':
          description: Ресурс не найден

  /_next/{resource}:
    get:
      tags: [Static]
      summary: Next.js статические ресурсы
      description: Внутренние ресурсы Next.js framework
      parameters:
        - name: resource
          in: path
          required: true
          schema:
            type: string
          description: Путь к Next.js ресурсу
      responses:
        '200':
          description: Next.js ресурс
          content:
            application/javascript:
              schema:
                type: string
            text/css:
              schema:
                type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Описание ошибки
          example: "Internal Server Error"
        message:
          type: string
          description: Детальное сообщение
          example: "Failed to proxy request to backend"
        timestamp:
          type: string
          format: date-time
          description: Время возникновения ошибки
      required:
        - error
        - timestamp