site_name: AquaStream Docs
repo_url: https://github.com/egorov-ma/aquastream
nav:
  - Home: index.md
  - Overview: overview.md
  - Architecture: architecture/index.md
  - Ops: ops/index.md
  - QA: qa/index.md
  - Glossary: glossary.md
  - Contributor Guide: contributor-guide.md
  - ADR: adr/index.md
  - Styleguides:
      - Markdown: styleguides/markdown_style.md
      - Versioning: styleguides/versioning.md
  - Roadmap: roadmap.md
  - API: api/index.md
  - Services:
      - Backend:
          - User:
              - Overview: modules/backend-user/backend-user-service/README.md
              - Runbook: modules/backend-user/backend-user-service/runbook.md
              - Changelog: modules/backend-user/backend-user-service/changelog.md
          - Event:
              - Overview: modules/backend-event/backend-event-service/README.md
              - Runbook: modules/backend-event/backend-event-service/runbook.md
              - Changelog: modules/backend-event/backend-event-service/changelog.md
          - Crew:
              - Overview: modules/backend-crew/backend-crew-service/README.md
              - Runbook: modules/backend-crew/backend-crew-service/runbook.md
              - Changelog: modules/backend-crew/backend-crew-service/changelog.md
          - Media:
              - Overview: modules/backend-media/backend-media-service/README.md
              - Runbook: modules/backend-media/backend-media-service/runbook.md
              - Changelog: modules/backend-media/backend-media-service/changelog.md
          - Notification:
              - Overview: modules/backend-notification/backend-notification-service/README.md
              - Runbook: modules/backend-notification/backend-notification-service/runbook.md
              - Changelog: modules/backend-notification/backend-notification-service/changelog.md
          - Payment:
              - Overview: modules/backend-payment/backend-payment-service/README.md
              - Runbook: modules/backend-payment/backend-payment-service/runbook.md
              - Changelog: modules/backend-payment/backend-payment-service/changelog.md
          - Gateway:
              - Overview: modules/backend-gateway/README.md
              - Runbook: modules/backend-gateway/runbook.md
              - Changelog: modules/backend-gateway/changelog.md
          - Common:
              - Overview: modules/backend-common/README.md
              - Runbook: modules/backend-common/runbook.md
              - Changelog: modules/backend-common/changelog.md
      - Frontend:
          - Overview: modules/frontend/README.md
          - Runbook: modules/frontend/runbook.md
          - Changelog: modules/frontend/changelog.md
      - Infra:
          - Overview: modules/infra/README.md
          - Runbook: modules/infra/runbook.md
          - Changelog: modules/infra/changelog.md
  - Internal notes:
      - Frontend:
          - AquaStream Frontend Spec: modules/frontend/aquastream-frontend-spec.md
          - Claude-ready brief: modules/frontend/claude-ready-brief.md
          - Finalization checklist: modules/frontend/frontend-finalization-checklist.md
          - Hardening & unification: modules/frontend/frontend-hardening-unification.md
          - Tailwind + shadcn unification: modules/frontend/tailwind-shadcn-unification.md
          - FE todos: modules/frontend/todos-fe.md
      - Infra:
          - CI README: modules/infra/CI-README.md
          - Developer Guide: modules/infra/DEVELOPER.md
          - Backend Spec (complete): modules/infra/aquastream-backend-spec-complete.md
  - FAQ: faq.md
theme:
  name: material
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.sections
    - toc.integrate
extra:
  version:
    provider: mike
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.caret
plugins:
  - search
  - mermaid2
  - redirects
