server:
  port: 8082

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/aquastream_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: event-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"

grpc:
  server:
    port: 9090
  reflection:
    enabled: true

grpcui:
  enabled: true
  path: /grpcui/  # URL для доступа к gRPC UI

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      service: event-service
      version: 1.0.0
    export:
      prometheus:
        enabled: true
        step: 10s
        descriptions: true
    distribution:
      percentiles-histogram:
        grpc.server.duration.seconds: true
        http.server.requests: true
      slo:
        grpc.server.duration.seconds: 50ms,100ms,200ms,500ms,1s,2s,5s
        http.server.requests: 50ms,100ms,200ms,500ms,1s,2s,5s

# Logging configuration
logging:
  level:
    org.aquastream.event: DEBUG
    net.devh.boot.grpc: DEBUG
    root: DEBUG

# AquaStream specific logging configuration
aquastream:
  logging:
    structured:
      enabled: false  # JSON logging disabled in dev
    level:
      root: DEBUG
  monitoring:
    grpc:
      enabled: true  # Enable gRPC monitoring
      detailed-metrics: true  # Enable detailed per-method metrics