server:
  port: 8082

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/aquastream_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

grpc:
  server:
    port: 9090
  reflection:
    enabled: true

grpcui:
  enabled: true
  path: /grpcui/  # URL для доступа к gRPC UI 