server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false # Отключаем Config Server
    gateway:
      routes:
        - id: user-service
          uri: http://aquastream-user:8081
          predicates:
            - Path=/users/**
        - id: planning-service
          uri: http://aquastream-planning:8082
          predicates:
            - Path=/planning/**
        - id: crew-service
          uri: http://aquastream-crew:8083
          predicates:
            - Path=/crew/**
        - id: notification-service
          uri: http://aquastream-notification:8084
          predicates:
            - Path=/notifications/**




















