server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: planning-service
          uri: http://localhost:8082
          predicates:
            - Path=/planning/**

        - id: crew-service
          uri: http://localhost:8083
          predicates:
            - Path=/crew/**

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**