spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-auth
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: user-api
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - JwtAuthentication
        - id: crew-service
          uri: http://crew-service:8083
          predicates:
            - Path=/api/crews/**
          filters:
            - StripPrefix=1
        - id: event-service
          uri: http://event-service:8082
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://notification-service:8084
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /api/swagger-ui.html
    enabled: true
    config-url: /api/docs/swagger-config
    urls:
      - name: "User Service"
        url: /api/users/api-docs
        display-name: "User Management API"
      - name: "Event Service"
        url: /api/events/api-docs
        display-name: "Event Management API"
      - name: "Crew Service"
        url: /api/crews/api-docs
        display-name: "Crew Management API"
      - name: "Notification Service"
        url: /api/notifications/api-docs
        display-name: "Notification API"
      - name: "Gateway"
        url: /api/docs
        display-name: "API Gateway"
  show-actuator: true
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080
