server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: crew-service
          uri: http://crew-service:8083
          predicates:
            - Path=/api/crews/**
          filters:
            - StripPrefix=1
        - id: event-service
          uri: http://event-service:8082
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://notification-service:8084
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /api/swagger-ui.html
    enabled: true
    config-url: /api/docs/swagger-config
    urls:
      - name: "User Service"
        url: /api/users/api-docs
        display-name: "User Management API"
      - name: "Event Service" 
        url: /api/events/api-docs
        display-name: "Event Management API"
      - name: "Crew Service"
        url: /api/crews/api-docs
        display-name: "Crew Management API"
      - name: "Notification Service"
        url: /api/notifications/api-docs
        display-name: "Notification API"
      - name: "Gateway"
        url: /api/docs
        display-name: "API Gateway"
  show-actuator: true

# Logging configuration for Docker environment
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.aquastream.gateway: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n" 