server:
  port: 0

# Actuator endpoints for testing
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging configuration for tests
logging:
  level:
    root: WARN