server:
  port: 8082

spring:
  application:
    name: event-service

grpc:
  server:
    port: 9090
  reflection:
    enabled: true

grpcui:
  enabled: true
  path: /grpcui/  # URL для доступа к gRPC UI 