server:
  port: 8103

spring:
  application:
    name: backend-crew
  profiles:
    active: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/aquastream
    username: aquastream
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: crew
  
  liquibase:
    change-log: classpath:migration/liquibase/master.xml
    contexts: dev
    default-schema: crew

app:
  crew:
    auto-assignment:
      enabled: true
      prefer-friends: true
      avoid-conflicts: true
    capacity-validation:
      strict: true
      allow-overbook: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.aquastream.crew: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE