FROM eclipse-temurin:21-jre
WORKDIR /app

# Copy boot jar built by Gradle
ARG JAR_FILE=build/libs/backend-gateway-*.jar
COPY ${JAR_FILE} app.jar

ENV JAVA_TOOL_OPTIONS "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]


