services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: aquastream
      POSTGRES_USER: aquastream
      POSTGRES_PASSWORD: aquastream
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  eureka-server:
    image: openjdk:21-slim
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  postgres_data: 