# Используем Node.js для сборки фронтенда
FROM node:20 AS build

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

# Копируем исходный код и собираем фронтенд
COPY frontend/ ./
RUN npm run build

# Используем Nginx для раздачи фронтенда
FROM nginx:latest
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]