version: '3.8'

services:
  backend-api:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.backend-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker 