server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    # Для локального запуска подключаемся к базе на localhost
    url: jdbc:postgresql://localhost:5432/aquastream_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your-256-bit-secret
  expiration: 86400000  # 24 часа 