server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: classpath:db-common.yml

jwt:
  secret: ${JWT_SECRET:default-secret-key-should-be-changed-in-production}
  expiration: ${JWT_EXPIRATION:86400000} 