server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/aquastream
    username: aquastream
    password: aquastream
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your-256-bit-secret
  expiration: 86400000 # 24 hours 