groups:
  # ========================================================================
  # АЛЕРТЫ БЕЗОПАСНОСТИ (Security Alerts)
  # ========================================================================
  - name: security_alerts
    rules:
      # Множественные неудачные аутентификации
      - alert: MultipleFailedLogins
        expr: increase(logstash_events_total{tags=~".*auth_event.*"}[5m]) > 10
        for: 2m
        labels:
          severity: warning
          category: security
          service: authentication
        annotations:
          summary: "Множественные неудачные попытки входа"
          description: "Обнаружено {{ $value }} неудачных попыток аутентификации за последние 5 минут"
          runbook_url: "https://docs.company.com/runbooks/security/failed-logins"

      # SQL инъекции
      - alert: SQLInjectionAttempt
        expr: increase(logstash_events_total{tags=~".*sql_injection_attempt.*"}[10m]) > 0
        for: 0m
        labels:
          severity: critical
          category: security
          attack_type: sql_injection
        annotations:
          summary: "🚨 Обнаружена попытка SQL-инъекции!"
          description: "Зафиксирована {{ $value }} попытка SQL-инъекции. Требуется немедленное расследование."
          runbook_url: "https://docs.company.com/runbooks/security/sql-injection"

      # XSS атаки
      - alert: XSSAttempt
        expr: increase(logstash_events_total{tags=~".*xss_attempt.*"}[10m]) > 0
        for: 0m
        labels:
          severity: critical
          category: security
          attack_type: xss
        annotations:
          summary: "🚨 Обнаружена попытка XSS атаки!"
          description: "Зафиксирована {{ $value }} попытка XSS атаки. Проверьте логи безопасности."
          runbook_url: "https://docs.company.com/runbooks/security/xss-attack"

      # Подозрительная активность по HTTP ошибкам
      - alert: HighHTTPErrorRate
        expr: (rate(nginx_http_requests_total{status=~"4..|5.."}[5m]) / rate(nginx_http_requests_total[5m])) * 100 > 20
        for: 3m
        labels:
          severity: warning
          category: security
          service: nginx
        annotations:
          summary: "Высокий процент HTTP ошибок"
          description: "{{ $value | humanizePercentage }} HTTP запросов завершаются с ошибками (4xx/5xx) за последние 5 минут"
          runbook_url: "https://docs.company.com/runbooks/security/http-errors"

      # Подозрительные географические запросы
      - alert: SuspiciousGeographicActivity
        expr: increase(logstash_events_total{geoip_country_name!~"Russia|Belarus|Kazakhstan"}[1h]) > 100
        for: 5m
        labels:
          severity: warning
          category: security
          type: geographic
        annotations:
          summary: "Подозрительная географическая активность"
          description: "{{ $value }} запросов из неожиданных географических регионов за последний час"

  # ========================================================================
  # АЛЕРТЫ ЗДОРОВЬЯ СЕРВИСОВ (Service Health Alerts)
  # ========================================================================
  - name: service_health
    rules:
      # Контейнер не работает
      - alert: ContainerDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          category: infrastructure
          component: container
        annotations:
          summary: "🔴 Контейнер {{ $labels.job }} недоступен"
          description: "Контейнер {{ $labels.job }} не отвечает на health checks более 1 минуты"
          runbook_url: "https://docs.company.com/runbooks/infrastructure/container-down"

      # Высокое использование CPU
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          category: performance
          resource: cpu
        annotations:
          summary: "Высокое использование CPU"
          description: "CPU использование {{ $value | humanizePercentage }} на {{ $labels.instance }}"

      # Высокое использование памяти
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 3m
        labels:
          severity: warning
          category: performance
          resource: memory
        annotations:
          summary: "Высокое использование памяти"
          description: "Использование памяти {{ $value | humanizePercentage }} на {{ $labels.instance }}"

      # Высокое использование диска
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 85
        for: 2m
        labels:
          severity: critical
          category: infrastructure
          resource: disk
        annotations:
          summary: "Критическое заполнение диска"
          description: "Диск {{ $labels.mountpoint }} заполнен на {{ $value | humanizePercentage }}"

  # ========================================================================
  # АЛЕРТЫ ПРИЛОЖЕНИЙ (Application Alerts)
  # ========================================================================
  - name: application_health
    rules:
      # PostgreSQL недоступен
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          category: database
          service: postgresql
        annotations:
          summary: "🔴 PostgreSQL недоступен"
          description: "База данных PostgreSQL не отвечает более 1 минуты"
          runbook_url: "https://docs.company.com/runbooks/database/postgresql-down"

      # Elasticsearch кластер не здоров
      - alert: ElasticsearchClusterUnhealthy
        expr: elasticsearch_cluster_health_status{color!="green"} == 1
        for: 2m
        labels:
          severity: warning
          category: search
          service: elasticsearch
        annotations:
          summary: "Elasticsearch кластер не в зеленом состоянии"
          description: "Статус кластера Elasticsearch: {{ $labels.color }}"

      # Kafka отстает по сообщениям
      - alert: KafkaConsumerLag
        expr: kafka_consumer_lag_sum > 1000
        for: 3m
        labels:
          severity: warning
          category: messaging
          service: kafka
        annotations:
          summary: "Большая задержка Kafka consumer"
          description: "Consumer lag составляет {{ $value }} сообщений"

      # Высокий процент ошибок в приложении
      - alert: HighApplicationErrorRate
        expr: (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])) * 100 > 5
        for: 3m
        labels:
          severity: warning
          category: application
          type: error_rate
        annotations:
          summary: "Высокий процент ошибок приложения"
          description: "{{ $value | humanizePercentage }} запросов завершаются с ошибками 5xx"

  # ========================================================================
  # АЛЕРТЫ МОНИТОРИНГА (Monitoring System Alerts)
  # ========================================================================
  - name: monitoring_health
    rules:
      # Prometheus target недоступен
      - alert: PrometheusTargetDown
        expr: up == 0
        for: 2m
        labels:
          severity: warning
          category: monitoring
          service: prometheus
        annotations:
          summary: "Prometheus target недоступен"
          description: "Target {{ $labels.job }} ({{ $labels.instance }}) недоступен более 2 минут"

      # Logstash не получает логи
      - alert: LogstashNoLogs
        expr: rate(logstash_events_total[5m]) == 0
        for: 5m
        labels:
          severity: warning
          category: logging
          service: logstash
        annotations:
          summary: "Logstash не получает логи"
          description: "Logstash не обрабатывал логи последние 5 минут"

      # Elasticsearch индексы растут слишком быстро
      - alert: ElasticsearchIndexGrowthHigh
        expr: increase(elasticsearch_indices_store_size_bytes[1h]) > 1073741824  # 1GB за час
        for: 0m
        labels:
          severity: warning
          category: storage
          service: elasticsearch
        annotations:
          summary: "Быстрый рост индексов Elasticsearch"
          description: "Размер индексов вырос на {{ $value | humanizeBytes }} за последний час"

  # ========================================================================
  # АЛЕРТЫ СЕТИ И ПОДКЛЮЧЕНИЙ (Network & Connectivity Alerts)
  # ========================================================================
  - name: network_alerts
    rules:
      # Высокая задержка сети
      - alert: HighNetworkLatency
        expr: avg_over_time(probe_duration_seconds[5m]) > 0.5
        for: 3m
        labels:
          severity: warning
          category: network
          type: latency
        annotations:
          summary: "Высокая задержка сети"
          description: "Средняя задержка {{ $value }}s для {{ $labels.instance }}"

      # Слишком много TCP соединений
      - alert: TooManyTCPConnections
        expr: node_netstat_Tcp_CurrEstab > 1000
        for: 5m
        labels:
          severity: warning
          category: network
          type: connections
        annotations:
          summary: "Слишком много TCP соединений"
          description: "{{ $value }} активных TCP соединений на {{ $labels.instance }}"

  # ========================================================================
  # АЛЕРТЫ РЕСУРСОВ И ЛИМИТОВ (Resource & Limits Alerts)
  # ========================================================================
  - name: resource_limits
    rules:
      # Контейнер превышает лимит памяти
      - alert: ContainerMemoryLimitNear
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 80
        for: 3m
        labels:
          severity: warning
          category: resources
          resource: memory
        annotations:
          summary: "Контейнер близок к лимиту памяти"
          description: "{{ $labels.name }} использует {{ $value | humanizePercentage }} от лимита памяти"

      # Контейнер превышает лимит CPU
      - alert: ContainerCPULimitNear
        expr: (rate(container_cpu_usage_seconds_total[5m]) / container_spec_cpu_quota * container_spec_cpu_period) * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: resources
          resource: cpu
        annotations:
          summary: "Контейнер близок к лимиту CPU"
          description: "{{ $labels.name }} использует {{ $value | humanizePercentage }} от лимита CPU"

      # Слишком много перезапусков контейнера
      - alert: ContainerRestartLoop
        expr: increase(kube_pod_container_status_restarts_total[15m]) > 3
        for: 0m
        labels:
          severity: critical
          category: stability
          type: restart_loop
        annotations:
          summary: "🔄 Контейнер в цикле перезапусков"
          description: "Контейнер {{ $labels.container }} перезапускался {{ $value }} раз за 15 минут"

  # ========================================================================
  # АЛЕРТЫ РЕЗЕРВНОГО КОПИРОВАНИЯ (Backup Alerts)
  # ========================================================================
  - name: backup_alerts
    rules:
      # Резервное копирование не выполнялось
      - alert: BackupNotCompleted
        expr: time() - backup_last_success_timestamp > 86400  # 24 часа
        for: 0m
        labels:
          severity: critical
          category: backup
          service: "{{ $labels.service }}"
        annotations:
          summary: "🚨 Резервное копирование не выполнялось"
          description: "Последний успешный бэкап {{ $labels.service }} был {{ $value | humanizeDuration }} назад"

      # Бэкап завершился с ошибкой
      - alert: BackupFailed
        expr: backup_success == 0
        for: 0m
        labels:
          severity: critical
          category: backup
          service: "{{ $labels.service }}"
        annotations:
          summary: "❌ Ошибка резервного копирования"
          description: "Резервное копирование {{ $labels.service }} завершилось с ошибкой"

  # ========================================================================
  # АЛЕРТЫ BUSINESS МЕТРИК (Business Metrics Alerts) 
  # ========================================================================
  - name: business_alerts
    rules:
      # Низкая активность пользователей
      - alert: LowUserActivity
        expr: rate(user_requests_total[1h]) < 10
        for: 15m
        labels:
          severity: warning
          category: business
          type: user_activity
        annotations:
          summary: "Низкая активность пользователей"
          description: "Только {{ $value }} запросов пользователей за последний час"

      # Высокое время ответа API
      - alert: HighAPIResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 3m
        labels:
          severity: warning
          category: performance
          component: api
        annotations:
          summary: "Высокое время ответа API"
          description: "95-й перцентиль времени ответа API: {{ $value }}s"