global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Правила алертов
rule_files:
  - "alert-rules.yml"
  - "grpc-alerts.yml"

# Конфигурация Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Spring Boot приложения с Actuator
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets:
          - api-gateway:8080
          - user-service:8081
          - event-service:8082
          - crew-service:8083
          - notification-service:8084

  # Специальный job для gRPC сервисов с детальными метриками  
  - job_name: 'grpc-services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets:
          - event-service:8082
          - crew-service:8083
    relabel_configs:
      - target_label: protocol
        replacement: 'grpc'
      - source_labels: [__address__]
        regex: 'event-service:8082'
        target_label: service_name
        replacement: 'event-service'
      - source_labels: [__address__]
        regex: 'crew-service:8083'
        target_label: service_name
        replacement: 'crew-service'
    metric_relabel_configs:
      # Сохраняем все gRPC метрики
      - source_labels: [__name__]
        regex: 'grpc_.*'
        action: keep
      # Сохраняем JVM метрики для анализа производительности
      - source_labels: [__name__]
        regex: 'jvm_.*'
        action: keep
      # Сохраняем HTTP метрики для REST endpoints
      - source_labels: [__name__]
        regex: 'http_.*'
        action: keep

  # Prometheus самомониторинг
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Logstash метрики
  - job_name: 'logstash'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['logstash:9600']

  # Elasticsearch метрики (если доступны)
  - job_name: 'elasticsearch'
    metrics_path: '/_prometheus/metrics'
    static_configs:
      - targets: ['elasticsearch:9200']
    basic_auth:
      username: 'elastic'
      password: 'changeMe123!'
    scheme: https
    tls_config:
      insecure_skip_verify: true

  # Nginx метрики (если настроен nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # PostgreSQL метрики (если настроен postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Node/System метрики (если настроен node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
