global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080', 'user-service:8081', 'planning-service:8082', 'crew-service:8083', 'notification-service:8084'] 