# Конфигурация источников данных для Grafana
# Автоматически подключает Prometheus и Alertmanager

apiVersion: 1

datasources:
  # Основной источник данных - Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager

  # Источник данных для алертов - Alertmanager
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    uid: alertmanager
    editable: false
    jsonData:
      implementation: prometheus