server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: classpath:db-common.yml
  kafka:
    bootstrap-servers: kafka:9092

jwt:
  secret: ${JWT_SECRET:CHANGE_ME_IN_PRODUCTION_DO_NOT_USE_THIS_VALUE_IT_IS_NOT_SECURE_ENOUGH_AND_NEEDS_TO_BE_CHANGED}
  expiration-ms: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
    
# SpringDoc OpenAPI конфигурация для Docker
springdoc:
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

# Logging configuration for Docker environment
logging:
  level:
    org.aquastream.user: INFO
    org.springframework.kafka: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n" 