server:
  port: 8083

spring:
  application:
    name: crew-service
  datasource:
    url: jdbc:postgresql://localhost:5432/aquastream_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

# AquaStream specific logging configuration  
aquastream:
  logging:
    structured:
      enabled: false  # JSON logging disabled in dev
    level:
      root: DEBUG
      
# Standard logging configuration
logging:
  level:
    org.aquastream.crew: DEBUG
    org.springframework.web: INFO
    root: DEBUG 