server:
  port: 8083

spring:
  application:
    name: crew-service
  config:
    import: classpath:db-common.yml
  datasource:
    url: jdbc:postgresql://postgres:5432/aquastream_db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

# SpringDoc OpenAPI конфигурация для Docker
springdoc:
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

# AquaStream specific logging configuration for Docker
aquastream:
  logging:
    structured:
      enabled: true  # JSON logging enabled in Docker
    level:
      root: INFO

# Standard Spring Boot logging (fallback)
logging:
  level:
    org.aquastream.crew: INFO
    org.springframework.web.servlet.DispatcherServlet: WARN
    org.springframework.boot.actuator.endpoint.web: WARN
    root: INFO