spring:
  config:
    import: classpath:db-common.yml
  application:
    name: crew-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
aquastream:
  logging:
    structured:
      enabled: false
    level:
      root: DEBUG
logging:
  level:
    org.aquastream.crew: DEBUG
    org.springframework.web: INFO
    root: DEBUG
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8083
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8083
