spring:
  config:
    import: classpath:db-common.yml
  application:
    name: crew-service
eureka:
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
aquastream:
  logging:
    structured:
      enabled: false
    level:
      root: DEBUG
logging:
  level:
    org.aquastream.crew: DEBUG
    org.springframework.web: INFO
    root: DEBUG
---
spring:
  config:
    activate:
      on-profile: local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8083
