server:
  port: 8084

spring:
  application:
    name: notification-service
  config:
    import: classpath:db-common.yml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name} 