server:
  port: 8102

spring:
  application:
    name: backend-event
  profiles:
    active: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/aquastream
    username: aquastream
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: event
  
  liquibase:
    change-log: classpath:migration/liquibase/master.xml
    contexts: dev
    default-schema: event

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.aquastream.event: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE