# Пример `docker-compose.override.yml` для локальной разработки.
# Используйте вместе с `docker-compose.dev.yml` и переопределяйте только необходимые параметры.

services:
  api-gateway:
    ports:
      - "8888:8080"     # Меняем внешний порт с 8080 на 8888

  frontend:
    ports:
      - "3001:80"       # Запускаем фронтенд на 3001

  user-service:
    environment:
      - SPRING_PROFILES_ACTIVE=local,dev
      - LOGGING_LEVEL_ROOT=DEBUG

# Аналогичным образом можно переопределять порты для Postgres, Kafka и других сервисов.

