openapi: 3.0.3
info:
  title: Crew Service API
  description: API для управления экипажами
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /crews:
    get:
      summary: Получить список экипажей
      operationId: getCrews
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Crew'
    post:
      summary: Создать новый экипаж
      operationId: createCrew
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrewRequest'
      responses:
        '201':
          description: Экипаж создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crew'
  /crews/{id}:
    get:
      summary: Получить экипаж по ID
      operationId: getCrewById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crew'
components:
  schemas:
    Crew:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - status
    CrewRequest:
      type: object
      properties:
        name:
          type: string
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
      required:
        - name
        - status 