openapi: 3.0.3
info:
  title: Gateway Service API
  description: API для управления маршрутизацией и доступом к микросервисам
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /routes:
    get:
      summary: Получить список доступных маршрутов
      operationId: getRoutes
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Route'
    post:
      summary: Создать новый маршрут
      operationId: createRoute
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouteRequest'
      responses:
        '201':
          description: Маршрут создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
  /routes/{id}:
    get:
      summary: Получить маршрут по ID
      operationId: getRouteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
components:
  schemas:
    Route:
      type: object
      properties:
        id:
          type: string
          format: uuid
        path:
          type: string
        serviceId:
          type: string
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - path
        - serviceId
        - status
    RouteRequest:
      type: object
      properties:
        path:
          type: string
        serviceId:
          type: string
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
      required:
        - path
        - serviceId
        - status 