name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend-*/**'
      - 'infra/**'
      - 'common/**'
      - '!frontend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend-*/**'
      - 'infra/**'
      - 'common/**'

jobs:
  test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: "**/build/reports/tests/**"
          if-no-files-found: ignore

  build:
    name: Backend Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JARs (skip tests)
        run: ./gradlew build -x test

      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: "**/build/libs/*.jar"

  compose-validate:
    name: Docker Compose Validate
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Validate docker-compose.yml
        run: docker compose -f infra/docker/compose/docker-compose.yml config 