---
name: Backend CI
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - 'backend-*/**'
      - 'common/**'
      - 'build.gradle'
      - 'gradle/**'
      - 'infra/docker/images/Dockerfile.backend-*'
  pull_request:
    branches: [main, develop]
    paths:
      - 'backend-*/**'
      - 'common/**'
      - 'build.gradle'
      - 'gradle/**'
      - 'infra/docker/images/Dockerfile.backend-*'

jobs:
  build:
    name: Backend Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build JARs
        run: ./gradlew build

      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: "**/build/libs/*.jar"

