name: CI Architecture & Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Gradle build (skip tests)
        run: ./gradlew --no-daemon --stacktrace build -x test

  archunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Run ArchUnit tests only
        run: |
          ./gradlew --no-daemon --stacktrace test --tests "*LayerRulesTest"
      - name: Upload test reports (ArchUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: archunit-test-reports
          path: |
            **/build/reports/tests/test

  deps-and-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Dependency updates report
        run: ./gradlew --no-daemon --stacktrace dependencyUpdates
      - name: OWASP Dependency-Check (skips without NVD key)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: ./gradlew --no-daemon --stacktrace dependencyCheckAnalyze
      - name: Upload OWASP reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: owasp-reports
          path: |
            **/build/reports/dependency-check-report.*
      - name: Run maintenance scripts
        run: |
          bash scripts/check-hardcoded-versions.sh || true
          bash scripts/list-duplicate-deps.sh || true
          bash scripts/check-unused-ext-versions.sh || true
