name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run unit tests
        run: ./gradlew test
        
      - name: Run integration tests
        run: ./gradlew integrationTest
        
      - name: Generate test reports
        if: always()
        run: ./gradlew jacocoTestReport
        
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            **/build/reports/tests/
            **/build/reports/jacoco/

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker images
        run: docker compose -f infra/docker/compose/docker-compose.yml build

  # TODO: Реализовать деплой в будущем, когда будет определена целевая среда
  # deploy:
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #
  #     - name: Deploy to production
  #       run: |
  #         echo "Здесь будет код для деплоя приложения" 