name: CI Dependency Locks

on:
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  write-locks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Write dependency locks
        run: ./gradlew --no-daemon --stacktrace dependencies --write-locks
      - name: Upload lockfiles
        uses: actions/upload-artifact@v4
        with:
          name: gradle-lockfiles
          path: |
            **/gradle.lockfile
