name: docs-version

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  no-op:
    runs-on: ubuntu-latest
    steps:
      - name: Versioning disabled
        run: echo "Docs versioning via mike is disabled; using GitHub Pages deploy only."
