name: docs-api

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/api/**'
      - 'contracts/**'
      - 'tools/generate_api_docs.py'
      - '.github/workflows/docs-api.yml'
      - 'mkdocs.yml'
  pull_request:
    paths:
      - '**/api/**'
      - 'contracts/**'
      - 'tools/generate_api_docs.py'
      - '.github/workflows/docs-api.yml'
      - 'mkdocs.yml'

jobs:
  api-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node.js for Spectral
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate API docs (ReDoc)
        run: |
          python -m pip install --upgrade pip
          python tools/generate_api_docs.py

      - name: Lint OpenAPI specs with Spectral (if any)
        run: |
          if [ -d docs/api/specs ]; then
            count=$(find docs/api/specs -type f \( -name '*.yaml' -o -name '*.yml' -o -name '*.json' \) | wc -l || true)
            if [ "$count" -gt 0 ]; then
              npx -y @stoplight/spectral-cli lint "docs/api/specs/**/*.{yaml,yml,json}" || exit 1
            else
              echo "No specs to lint"
            fi
          else
            echo "No specs directory"
          fi

      - name: Upload API docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: |
            docs/api/**

      - name: Drift check for generated API docs
        run: |
          git add -N docs/api || true
          CHANGED=$(git status --porcelain=1 docs/api | wc -l | tr -d ' ')
          if [ "$CHANGED" -ne 0 ]; then
            echo "::error file=docs/api::Generated API docs changed. Please run 'make docs-api' and commit updates.";
            echo "Changed files:";
            git status --porcelain=1 docs/api;
            exit 1;
          fi
