name: docs-inventory

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
      - 'tools/inventory_md.py'
      - '.github/workflows/docs-inventory.yml'
  pull_request:
    paths:
      - '**/*.md'
      - 'tools/inventory_md.py'
      - '.github/workflows/docs-inventory.yml'

jobs:
  inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate inventory
        run: |
          python -m pip install --upgrade pip
          python tools/inventory_md.py --repo-root . --csv docs/_inventory/md_inventory.csv --json docs/_inventory/md_inventory.json

      - name: Upload inventory artifact
        uses: actions/upload-artifact@v4
        with:
          name: md-inventory
          path: docs/_inventory/*

      - name: Check drift
        run: |
          git diff --exit-code docs/_inventory/md_inventory.csv docs/_inventory/md_inventory.json || (echo "::error file=docs/_inventory::Inventory changed. Please commit updated files (run 'make docs-inventory')." && exit 1)
