name: Docs CI

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'docs/docs-tools/mkdocs.yml'
      - 'docs/docs-tools/requirements-docs.txt'
      - 'docs/docs-tools/tools/**'
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'docs/docs-tools/mkdocs.yml'
      - 'docs/docs-tools/requirements-docs.txt'
      - 'docs/docs-tools/tools/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-docs.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/docs-tools/requirements-docs.txt

      - name: Build MkDocs
        run: |
          cd docs/docs-tools && mkdocs build --strict

      - name: Upload site artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: site
          path: ./build/docs
