name: Sync Labels

on:
  push:
    branches: [ main ]
    paths:
      - '.github/labels.yml'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

concurrency:
  group: labels-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Sync labels from .github/labels.yml
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5
        with:
          yaml-file: .github/labels.yml
          skip-delete: false
