name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/labeler.yml'
      - '.github/workflows/labeler.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels based on changes
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v5
        with:
          sync-labels: true
          configuration-path: .github/labeler.yml

      - name: Summary
        shell: bash
        run: |
          echo "### PR Labeler — итог" >> "$GITHUB_STEP_SUMMARY"
          echo "- Применены метки согласно .github/labeler.yml" >> "$GITHUB_STEP_SUMMARY"
