name: Labels Sync

on:
  push:
    branches: [ main ]
    paths:
      - '.github/labels.yml'
      - '.github/workflows/label-sync.yml'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Sync labels from .github/labels.yml
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5
        with:
          yaml-file: .github/labels.yml
          skip-delete: false

      - name: Summary
        shell: bash
        run: |
          echo "### Labels — синхронизация" >> "$GITHUB_STEP_SUMMARY"
          echo "- Набор меток обновлён по .github/labels.yml" >> "$GITHUB_STEP_SUMMARY"
