name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name to release (e.g., v1.2.3). If empty, uses current tag context.'
        required: false
        type: string
      draft:
        description: 'Create draft release'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - name: Compute tag
        id: meta
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.tag }}" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            echo "::error::No tag detected. Provide 'tag' input when manually dispatching or push a tag like v1.2.3.";
            exit 1
          fi
          echo "tag_name=${TAG}" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2
        with:
          tag_name: ${{ steps.meta.outputs.tag_name }}
          generate_release_notes: true
          draft: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.draft == 'true' }}
