---
name: Security Scan

permissions:
  contents: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM
  push:
    branches: [main]
    paths:
      - 'infra/docker/images/**'
      - '.github/workflows/security.yml'

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java and Node.js
        uses: ./.github/actions/setup-java-node

      - name: Build backend modules
        run: |
          ./gradlew build -x test

      - name: Upload backend JARs
        uses: actions/upload-artifact@v4
        with:
          name: backend-jars
          path: backend-*/build/libs/*.jar

  docker-security-scan:
    name: Docker Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build-backend
    strategy:
      fail-fast: false
      matrix:
        service: [backend-user, backend-gateway, backend-event, backend-notification, backend-crew, frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Trivy vulnerability database
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}
          restore-keys: trivy-db-

      - name: Set up Java and Node.js
        uses: ./.github/actions/setup-java-node

      - name: Download backend JARs
        if: matrix.service != 'frontend'
        uses: actions/download-artifact@v4
        with:
          name: backend-jars
          path: .

      - name: Build frontend application
        if: matrix.service == 'frontend'
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Build Docker image (Backend)
        if: matrix.service != 'frontend'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/images/Dockerfile.${{ matrix.service }}
          tags: aquastream-${{ matrix.service }}:security-scan
          # Use explicit Temurin tags to match Dockerfiles
          build-args: |
            ECLIPSE_TEMURIN_JDK_TAG=21-jdk-alpine
            ECLIPSE_TEMURIN_JRE_TAG=21-jre-alpine
          load: true
          # Cache Docker layers to speed up builds
          cache-from: type=gha,scope=${{ matrix.service }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service }}

      - name: Build Docker image (Frontend)
        if: matrix.service == 'frontend'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/images/Dockerfile.frontend
          tags: aquastream-frontend:security-scan
          load: true
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: aquastream-${{ matrix.service }}:security-scan
          format: sarif
          output: trivy-${{ matrix.service }}-results.sarif
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Upload scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-${{ matrix.service }}-results.sarif
