---
name: Lint Infrastructure

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - '.github/workflows/**'
      - 'infra/**'
      - '*.sh'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'infra/**'
      - '*.sh'

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.7

  infrastructure-lint:
    name: Lint Infrastructure Files
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        env:
          POSTGRES_PASSWORD: test_password_123
          GRAFANA_ADMIN_PASSWORD: test_password_123
          ELASTIC_PASSWORD: test_password_123
          KIBANA_PASSWORD: test_password_123
        run: |
          docker compose -f infra/docker/compose/docker-compose.yml \
            --env-file <(printf "POSTGRES_PASSWORD=%s\nGRAFANA_ADMIN_PASSWORD=%s\nELASTIC_PASSWORD=%s\nKIBANA_PASSWORD=%s\n" "$POSTGRES_PASSWORD" "$GRAFANA_ADMIN_PASSWORD" "$ELASTIC_PASSWORD" "$KIBANA_PASSWORD"; tail -n +5 infra/docker/compose/.env.ci) \
            config --quiet

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v2

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.*
          recursive: true

      - name: Validate YAML files
        uses: mikefarah/yq@v4
        with:
          cmd: |
            find infra \( -name '*.yml' -o -name '*.yaml' \) -exec yq eval '.' {} + > /dev/null
