---
name: Lint Infrastructure

'on':
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - '.github/workflows/**'
      - 'infra/**'
      - '*.sh'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'infra/**'
      - '*.sh'

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.7

  infrastructure-lint:
    name: Lint Infrastructure Files
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: dotenvx/dotenv-action@v2
        with:
          path: infra/docker/compose/.env.example
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD || 'test' }}
          GRAFANA_ADMIN_PASSWORD: >-
            ${{ secrets.GRAFANA_ADMIN_PASSWORD || 'test' }}
          ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD || 'test' }}
          KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD || 'test' }}

      - name: Validate Docker Compose
        run: |
          docker compose -f infra/docker/compose/docker-compose.dev.yml config --quiet
          docker compose -f infra/docker/compose/docker-compose.full.yml config --quiet

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v2

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.*
          recursive: true

      - name: Validate YAML files
        uses: mikefarah/yq@v4
        with:
          cmd: |
            find infra \( -name '*.yml' -o -name '*.yaml' \) \
              -exec yq eval '.' {} + > /dev/null
