---
name: Lint Infrastructure

'on':
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - '.github/workflows/**'
      - 'infra/**'
      - '*.sh'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'infra/**'
      - '*.sh'

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@v1.7.7

  infrastructure-lint:
    name: Lint Infrastructure Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint YAML files
        uses: mikefarah/yq@v4
        with:
          cmd: >-
            for file in $(find infra -name '*.yml' -o -name '*.yaml'); do
              echo "Checking: $file";
              yq eval '.' "$file" >/dev/null;
            done

      - name: Lint shell scripts
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: frontend/node_modules

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: infra/docker/images
          recursive: true

      - name: Prepare environment for validation
        run: |
          # Создаем .env файл из .env.example с тестовыми паролями для валидации
          sed 's/POSTGRES_PASSWORD=$/POSTGRES_PASSWORD=test_password_123/' infra/docker/compose/.env.example | \
          sed 's/GRAFANA_ADMIN_PASSWORD=$/GRAFANA_ADMIN_PASSWORD=test_password_123/' | \
          sed 's/ELASTIC_PASSWORD=$/ELASTIC_PASSWORD=test_password_123/' | \
          sed 's/KIBANA_PASSWORD=$/KIBANA_PASSWORD=test_password_123/' > infra/docker/compose/.env

      - name: Quick infrastructure validation
        run: |
          if [ -f "infra/scripts/validate-infrastructure.sh" ]; then
            chmod +x infra/scripts/validate-infrastructure.sh
            ./infra/scripts/validate-infrastructure.sh --quick
          fi
