---
name: Lint Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - '.github/workflows/**'
      - 'infra/**'
      - '*.sh'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'infra/**'
      - '*.sh'

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.7

  infrastructure-lint:
    name: Lint Infrastructure Files
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install linting tools
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          
          sudo apt-get update
          sudo apt-get install -y shellcheck
          
          sudo wget -qO /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /usr/local/bin/hadolint

      - name: Lint YAML files
        run: |
          find infra -name "*.yml" -o -name "*.yaml" | while read -r yaml_file; do
            echo "Checking: $yaml_file"
            yq eval '.' "$yaml_file" > /dev/null
          done

      - name: Lint shell scripts
        run: |
          find . -name "*.sh" -not -path "./node_modules/*" | while read -r script; do
            echo "Checking: $script"
            shellcheck -x "$script"
          done

      - name: Lint Dockerfiles
        run: |
          find infra/docker/images -name "Dockerfile.*" | while read -r dockerfile; do
            echo "Checking: $dockerfile"
            hadolint "$dockerfile"
          done

      - name: Prepare environment for validation
        env:
          POSTGRES_PASSWORD: test_password_123
          GRAFANA_ADMIN_PASSWORD: test_password_123
          ELASTIC_PASSWORD: test_password_123
          KIBANA_PASSWORD: test_password_123
        run: envsubst < infra/docker/compose/.env.ci > infra/docker/compose/.env

      - name: Quick infrastructure validation
        run: |
          if [ -f "infra/scripts/validate-infrastructure.sh" ]; then
            chmod +x infra/scripts/validate-infrastructure.sh
            ./infra/scripts/validate-infrastructure.sh --quick
          fi
